# Generated by Django 3.2.3 on 2021-05-25 18:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cources',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courseServer_id', models.CharField(max_length=10)),
                ('date', models.CharField(max_length=50)),
                ('modified', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=1000)),
                ('content', models.CharField(blank=True, max_length=10000)),
                ('contentProtected', models.BooleanField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AuthorServer_id', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=10000)),
                ('url', models.CharField(max_length=500)),
                ('AuthorData', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='AuthorData', to='Cources.cources')),
            ],
        ),
    ]
