# Generated by Django 3.2.3 on 2021-05-25 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyFeeds',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('User_id', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('date', models.CharField(max_length=50)),
                ('component', models.CharField(max_length=50)),
                ('type', models.CharField(max_length=500)),
                ('status', models.CharField(max_length=500)),
                ('favorited', models.CharField(max_length=50)),
                ('can_favorite', models.CharField(max_length=10)),
                ('favorite_count', models.CharField(max_length=50)),
                ('can_comment', models.CharField(max_length=10)),
                ('can_edit', models.CharField(max_length=10)),
                ('group_id', models.CharField(max_length=10)),
                ('content_stripped', models.TextField()),
                ('privacy', models.CharField(max_length=10)),
                ('group_name', models.CharField(max_length=10)),
                ('comment_count', models.CharField(max_length=10)),
                ('can_delete', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Mygroup',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('groupid', models.CharField(max_length=50, unique=True)),
                ('date', models.CharField(max_length=50)),
                ('date_gmt', models.CharField(max_length=50)),
                ('modified', models.CharField(max_length=500)),
                ('modified_gmt', models.CharField(max_length=500)),
                ('content', models.CharField(blank=True, max_length=50, null=True)),
                ('content_protected', models.CharField(max_length=6)),
                ('slug', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=10)),
                ('title', models.CharField(max_length=500)),
            ],
        ),
    ]
