# Generated by Django 3.2.3 on 2021-05-25 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Groups', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='myfeeds',
            old_name='User_id',
            new_name='user_id',
        ),
        migrations.AlterField(
            model_name='myfeeds',
            name='content_stripped',
            field=models.CharField(max_length=500),
        ),
    ]
