# Generated by Django 3.2.3 on 2021-05-25 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Groups', '0002_auto_20210525_1822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myfeeds',
            name='group_name',
            field=models.CharField(max_length=50),
        ),
    ]
