# Generated by Django 3.2.3 on 2021-05-26 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Groups', '0003_alter_myfeeds_group_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='myfeeds',
            name='comment_id',
            field=models.CharField(default=2, max_length=50),
            preserve_default=False,
        ),
    ]
