from django.db import models


class Mygroup(models.Model):
    id = models.BigAutoField(primary_key=True)
    groupid = models.CharField(unique=True, max_length=50)
    date = models.CharField(max_length=50)
    date_gmt = models.CharField(max_length=50)
    modified = models.CharField(max_length=500)
    modified_gmt = models.CharField(max_length=500)
    content = models.CharField(max_length=50, blank=True, null=True)
    content_protected = models.CharField(max_length=6)
    slug = models.CharField(max_length=50)
    status = models.CharField(max_length=10)
    title = models.CharField(max_length=500)


class MyFeeds(models.Model):
    user_id = models.CharField(max_length=50)
    name = models.CharField(max_length=50)
    date = models.CharField(max_length=50)
    comment_id = models.CharField(max_length=50)
    component = models.CharField(max_length=50)
    type = models.CharField(max_length=500)
    status = models.CharField(max_length=500)
    favorited = models.CharField(max_length=50)
    can_favorite = models.CharField(max_length=10)
    favorite_count = models.CharField(max_length=50)
    can_comment = models.CharField(max_length=10)
    can_edit = models.CharField(max_length=10)
    group_id = models.CharField(max_length=10)
    can_delete = models.CharField(max_length=10)
    content_stripped = models.CharField(max_length=500)
    privacy = models.CharField(max_length=10)
    group_name = models.CharField(max_length=50)
    comment_count = models.CharField(max_length=10)
    can_delete = models.CharField(max_length=50)


class MyFeedsComments(models.Model):
    comments = models.ForeignKey(MyFeeds, related_name='tracks', on_delete=models.CASCADE)
    user_id = models.CharField(max_length=50)
    name = models.CharField(max_length=50)
    date = models.CharField(max_length=50)
    component = models.CharField(max_length=50)
    type = models.CharField(max_length=500)
    status = models.CharField(max_length=500)
    favorited = models.CharField(max_length=50)
    can_favorite = models.CharField(max_length=10)
    favorite_count = models.CharField(max_length=50)
    can_comment = models.CharField(max_length=10)
    can_edit = models.CharField(max_length=10)
    group_id = models.CharField(max_length=10)
    can_delete = models.CharField(max_length=10)
    content_stripped = models.CharField(max_length=500)
    privacy = models.CharField(max_length=10)
    group_name = models.CharField(max_length=50)
    comment_count = models.CharField(max_length=10)
    can_delete = models.CharField(max_length=50)
